name: 'Setup VCPKG'
description: 'Setup VCPKG'
author: 'Jared Irwin'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'code'
  color: 'purple'

# Define your inputs here.
inputs:
  vcpkg-root:
    description: 'Location of vcpkg'
    required: true
  use-cache:
    description: 'Use Actions cache'
    default: 'true'
  preinstall-dependencies:
    description: 'Install dependencies for project'
    default: 'false'
  install-location:
    description: 'Location to install dependencies'

runs:
  using: node20
  main: dist/index.js
